#!/bin/bash
ledPin=$1
if [ $# -eq 1 ];then
        /show/colecho "Blink LED $ledPin" $WARN
        /do/led/python/blink.py $ledPin 3 0.1
else
	if [ $# -eq 3 ];then
	loopUntil=$2
	speed=$3
	/do/led/python/blink.py $ledPin $loopUntil $speed
	else
	        /show/errorBox "Choose a BCM pin"
	        gpio readall
        	exit 1
	fi
fi


