#!/bin/bash
ledPin=$1
if [ $# -eq 1 ];then
        /show/colecho "Blink LED $ledPin" $WARN
        /opt/piget/led/bin/blink $ledPin 100 2
else
        /show/errorBox "Choose a WpI pin"
        gpio readall
        exit 1
fi


