#!/bin/bash
if [ $# -ne 0 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [gpio] [led] [electronics]"
		/show/usageDescription "Install led module (wiringPi)"
		/show/usage "$0"
		exit 1
else
		/show/description "[LED] Install"
		/system/installWiringPi
fi