#!/bin/bash
#Turn a led off
ledPin=$1
if [ $# -eq 1 ];then
        /show/listecho "Turn off LED $ledPin" $ERR
        /do/led/python/onoff.py $ledPin 0
else
        /show/errorBox "Choose a bcm pin"
        gpio readall
        exit 1
fi

