#!/bin/bash
#Turn a led off
ledPin=$1
if [ $# -eq 1 ];then
        /show/listecho "Turn off LED $ledPin" $ERR
        /do/led/python/onoff.py $ledPin 0
else
	    /show/gpio
	    /show/errorBox "Choose a pin"
        exit 1
fi

