#!/bin/bash

# Piget Documentation
if [ $# -ge 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
		/show/messagebox "$0"
		/show/info "[beta] [gpio] [led] [electronics]"
		/show/usageDescription "Turn on a led"
		/show/usage "$0 pin"
		/show/example "$0 21"
		exit 1
else	

#If there is an argument (led gpio)
	if [ $# -eq 1 ];then
	    ledPin=$1
	    /show/listecho "Turn on LED $ledPin" $OK #Display text
	    /do/led/python/onoff.py $ledPin 1 #Turn on led
	else
	    /show/gpio #Display GPIO
	    /show/listecho "Could you tell me where the led is plugged ?" $WARN
	    exit 314
	fi
fi
