#!/bin/bash

# Piget Documentation
if [ $# -ge 2 ] || [[ $1 == "--help" ]] || [ $(id -u) -ne 0 ];then
	/show/messagebox "$0"
	/show/info "[beta] [gpio] [led] [electronics] [orangepi]"
	/show/usageDescription "Turn on a led"
	/show/usage "$0 pin"
	/show/example "$0 21"
	exit 1
else	

	hardware=$(/pi/getBoard)

#If there is an argument (led gpio)
if [ $# -eq 1 ];then
	ledPin=$1
	    /show/listecho "Turn on LED $ledPin" $OK #Display text
	    
	    if [[ $hardware == "orangepi" ]];then
	    	ledPin=$(/system/h3ToBcm $ledPin)
			/do/led/python/onoff_orange.py $ledPin 1 #Turn on led
		else
	        /do/led/python/onoff.py $ledPin 1 #Turn on led
	    fi
	else
	    /show/gpio #Display GPIO
	    /show/listecho "Could you tell me where the led is plugged ?" $WARN
	    exit 314
	fi
fi
