#!/bin/bash
ledPin=$1
if [ $# -eq 1 ];then
        /show/colecho "Pulse LED $ledPin" $WARN
        /do/led/python/pulse.py $ledPin 2
else
	if [ $# -eq 2 ];then
	speed=$2
	/do/led/python/pulse.py $ledPin $speed
	else
	        /show/gpio
	        /show/errorBox "Choose a pin"
        	exit 1
	fi
fi
